### ISSUE TITLE
Compatibility with ColdFusion 2018

### ISSUE THREAD

**Issue by joshuacurtiss** [jsteinshouer/cf-jwt-simple#2]
Greetings!  As I begin testing our systems to upgrade to CF 2018, I came across a breaking bug in cf-jwt-simple. The cause appears to be with `epochTimeToLocalDate` function's implementation of `java.util.Date`, which behaves differently in CF 2018 likely because of the new version of Java.

The error is, "The init method was not found", with the critical hint, "ColdFusion found 2 methods that match the provided arguments." Presumably CF can't decide whether to pass the number as a string or as a long to Java's overloaded constructor. 

Offending code: 
```
createObject("java", "java.util.Date").init(epoch*1000)
```

This change eliminates the confusion for CF and fixes it:
```
createObject("java", "java.util.Date").init(javaCast("long",epoch*1000))
```

Alternatively, sticking with CF-native function operates the same and may be less likely to break in future again:
```
dateAdd("s",epoch,"Jan 1, 1970")
```

I understand your stated reason for the Java route and either route has pros and cons.

Just sharing and hope you can patch this so I can keep the library as I update to CF 2018.  Thanks so much. 

Josh

**Comment by jsteinshouer** [comment]
@joshuacurtiss Thanks for reporting this. I merged the fix into master and updated the version. Let me know if you have any issues with it.

**Comment by joshuacurtiss** [comment]
It works. Thanks so much.
